### 아침에 정자, 판교역에 내릴 사람 예측하기 
* 매일 아침 동천역(용인/수지) -> 잠실역 까지 출근을 하는데
* 매일 하는 고민중에 하나가 동천역->강남에서 정자, 판교에 내릴사람을 선택하여 앉아서 가는것이다. 
* 정자/판교에 내릴사람은 왠지 나와 같은 프리한 옷차림의 개발자들이 겠지하고 그런 사람들 앞에 서는데 
* 정말 그럴까 고민이 든다 그래서 직접 데이터를 수집하고 측정해 봤다..

### 데이터 수집 

* 최근 한달동안 5개의 특징으로 남녀, 나이대, 옷차림, 행동, 이어폰여부를 한 좌석라인(7명)으로 측정하였다. 
* 측정 범례
<pre>
좌석은 서서 보는 시점에서 왼-> 오 순서
여성,남성,
숫자 나이대,
정장, 세미정장, 평(상복)
핸(드폰보기), 생(각중), 토(크), 책(읽기), 노(트북) 
이(어폰) , 노(싱), 
판(교), 정(자), (자리)양(보) 
</pre>

* 수집한 Raw 데이터 
{platform-number} / {datetime} / {start:station}-{end:station} / {남|녀}{2|3|4|5|6}{정|세|평}{핸|책|잠|생}{노|이}
<pre>
2-1 / 2017-07-13 07:30 / 동천 -> 강남 / 여3정핸노 남4정핸노 남3정잠이 남3세핸이 여3세노이:판 여5평핸노:판 남3정잠이
2-1 / 2017-07-14 08:25 / 동천 -> 강남 / 남3정핸노 남4세핸이백:판:성공 남4평핸노:정 여5평잠노 남3평잠노 여3세핸이 여3평핸노 
2-1 / 2017-07-17 08:17 / 동천 -> 강남 / 여2핸평이:정 여3잠세이:판 남4잠세노 여3핸세노 남3책평이 여4잠세노:판  여3현세이
2-1 / 2017-07-18 08:40 / 동천 -> 강남 / 여2핸평이:정 남3핸세노 남4핸평노:정 남2핸평노 여3잠세노 여2핸평노 여3핸평노:정
2-1 / 2017-07-19 08:20 / 동천 -> 강남 / 여2핸평이:판 여2핸평이 여2잠평노 남4잠정노 여3잠정노 여3핸평이 여4현세이
2-1 / 2017-07-20 08:06 / 동천 -> 강남 / 남5잠세노:정 여3잠평노 남3핸평이:판 여4생세노:정 남3핸세노 여5잠세노 남6생세노
2-1 / 2017-07-21 07:30 / 동천 -> 강남 / 남4핸세노 남4핸평이 여3핸세이 남4정잠노 여4생세노 남3핸평이:정 여3잠세노
2-1 / 2017-07-24 07:35 / 동천 -> 강남 / 여3잠평이 여4평핸노 남4현장노 여3핸세노 여4핸평노:판 여3핸평이:판 남4핸평노:정 
2-1 / 2017-07-25 07:43 / 동천 -> 강남 / 여4토세노 남5토세노 남4잠세노 남4잠평노:정 남3핸평이 남3잠정이 여4생세노:양
2-1 / 2017-07-26 08:15 / 동천 -> 강남 / 여3핸평이 남2책평이 여3핸세이 남5핸세노 여5핸세이 남3책세노 여2노평이 
2-1 / 2017-07-27 08:35 / 동천 -> 강남 / 남3생평노:판 여3핸평노 남4잠평노 남4잠정노 여4잠세노:판 남6생세노 남4핸평이:판
2-1 / 2017-07-31 08:25 / 동천 -> 강남 / 남3생평이:판 남4책평노:정 여3핸평이 남4핸세노 여3핸평이 남4핸평이 여2핸평이
2-1 / 2017-08-02 07:12 / 동천 -> 강남 / 여3잠평이 여3핸평이 남4책평노 남4핸평이 남6현세이 남6잠생이 남2핸평이
2-1 / 2017-08-03 08:20 / 동천 -> 강남 / 남3핸평이:판 남3핸평노:정 남4핸세이 남5잠세노 여2핸세이 남3핸평노 여5잠세노
2-1 / 2017-08-08 07:48 / 동천 -> 강남 / 남4핸정이 남4핸평노 여4책세노 남5핸평노 남4핸평이 남6핸세노 여2핸평이
2-1 / 2017-08-09 08:02 / 동천 -> 강남 / 여3잠세노:정 남4잠세노 남4책평이 남4핸정이 남2잠평노 남3핸세노 여3잠세노
2-1 / 2017-08-10 07:35 / 동천 -> 강남 / 남2생세노:정 남2생평노:판 여4잠평노 남4핸평노 남4핸세노 여3핸세노 남3핸세이
2-1 / 2017-08-11 07:12 / 동천 -> 강남 / 남3책평노 남4핸세노 남4핸정노 여3생세노 남3생정노 여3잠세노 여3잠평노:판
2-1 / 2017-08-14 08:40 / 동천 -> 강남 / 여2핸평이 여3잠평노:판 여3핸평이 남4핸세노 남3핸평노 남3잠평노 여3핸세노
2-1 / 2017-08-16 07:35 / 동천 -> 강남 / 여4핸세노 남3핸세노 여5책세노 남3핸평이 남6잠세노 남3핸평이:정 여3잠세노
2-1 / 2017-08-17 08:52 / 동천 -> 강남 / 여3핸평노 남3핸평이:판교 남4핸평이 여5잠세노 남2핸평이:판 여3핸평노 여3핸세노
2-1 / 2017-08-18 08:35 / 동천 -> 강남 / 남4잠평이 여3핸평노 여3잠평노:판 여3토정노 여2토정노 남3토정노 여2핸평노:판
2-1 / 2017-08-22 08:20 / 동천 -> 강남 / 남3잠평노:판 남4핸정노 여2잠평노 여5잠세노 남5잠세노 여2핸세이 여3핸평노
2-1 / 2017-08-23 07:48 / 동천 -> 강남 / 남3핸세노:정 여4핸세노 여3핸세노 여3잠세이 남4핸평노 녀3핸평이 남4잠세이
2-1 / 2017-08-25 07:52 / 동천 -> 강남 / 남4잠평노 남4잠평노:정 여4잠평노 남3핸평노 남6핸세이 남3핸정이 여4핸평이:판
2-1 / 2017-08-28 08:10 / 동천 -> 강남 / 여4핸평노 남3핸세노 여2핸세이 여3책세노 남1핸평이:정 남1생평이:정 여3잠평이
2-1 / 2017-08-29 08:35 / 동천 -> 강남 / 남4잠정이 여4핸세노 남4잠세이 여3잠평노 남4핸평이 여2핸평노 남4현세이
2-1 / 2017-08-30 08:10 / 동천 -> 강남 / 여5책세노 여3핸세이 남5핸평노 여3핸평노 여2핸세이 여3핸평이 여2핸평노
2-1 / 2017-08-31 08:19 / 동천 -> 강남 / 남4핸평이 여3잠평노 여3핸평이 남5핸평이 여4핸세이 남3핸세노 여3핸세노 
2-1 / 2017-09-04 07:52 / 동천 -> 강남 / 남4핸평이:정 남3잠평노 남5잠세이 남4핸평노:판 남4핸정이:정 여3핸평이 여3잠평노 
2-1 / 2017-09-05 08:35 / 동천 -> 강남 / 여2핸평노 여3평핸노:판 여2핸세이 남4책평노 여6책세노 여3핸평이:판 여5잠세노 
2-1 / 2017-09-06 07:40 / 동천 -> 강남 / 남4핸세이 남4핸평이:정 남4잠세노 남4생세이:정 남4핸평노:판교 남4잠정노 여4핸세이
2-1 / 2017-09-07 08:21 / 동천 -> 강남 / 여4잠세노:정 여4핸평노:정 여3잠평이 여3잠평이 여2핸평이 여3핸평노 여4잠평노 
2-1 / 2017-09-08 07:45 / 동천 -> 강남 / 여3잠평노 여3핸평노:정 남3잠평노 남3핸평이:판 여4핸평이 남3잠평이 여3잠세이
2-1 / 2017-09-11 08:30 / 동천 -> 강남 / 남4핸평노 남3핸평이:판 여3핸평이:판 남3잠평노 남1핸평이:정 남1핸평노:정 여3핸평노:판
2-1 / 2017-09-12 08:07 동천 -> 강남 / 여3핸평이 남4핸세이:정 여3핸평이 남4핸세이 남4잠평이 여3잠평이 여6토평노 
2-1 / 2017-09-13 07:40 / 동천 -> 강남 / 여3핸평이:판 여4잠평노 여3핸평이 여3잠평이 남3잠정노 여3잠평이 여3핸평이
2-1 / 2017-09-14 07:24 / 동천 -> 강남 / 남3잠평이 남3핸평이 여4핸평노 여2핸평이 여4핸평노 여6생평노 남5생세노:정
2-1 / 2017-09-15 08:20 / 동천 -> 강남 / 여2잠평이:정 여3잠세노 여3핸세노 여4잠세노 남3핸평노 여3잠세노 여3핸평이:판
2-1 / 2017-09-18 07:07 / 동천 -> 강남 / 남5책평노:판 남5핸세노 남3핸평이 남4잠세노 남5책세노 남2핸평노 여3잠평이
2-1 / 2017-09-19 08:28 / 동천 -> 강남 / 남4핸평이 남4핸평이 여3책평이 남4생평이 여3핸평이 여4잠평노 여3핸평노:판
2-1 / 2017-09-20 07:44 / 동천 -> 강남 / 남2핸평이 여3핸평이 여2잠세노 남2잠평이 여4핸세노 남3생세노:정 여3핸평이
2-1 / 2017-09-22 07:18 / 동천 -> 강남 / 여4핸평노:판 남4핸평이 남4잠평노 여3핸평이 여2생평이 남5핸세이 남5핸정노
2-1 / 2017-09-27 07:24 / 동천 -> 강남 / 여3잠평노 여4잠평노:정 남5잠정노 남3핸평노:판 남3잠평노 남3핸평노 여2핸세이
2-1 / 2017-09-28 07:13 / 동천 -> 강남 / 남5책평노:판 남4잠세노 여3핸평노 남5생세이 남4핸세노 남4잠세노 여3핸평노
2-1 / 2017-09-29 08:11 동천 -> 강남 / 여3핸세이:정 여3핸평이 남2잠정노 남4핸정이 남4핸평노 남5잠세이 남3핸평노:정
</pre>

In [1]:
import pandas as pd    
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

sns.set(style="whitegrid", context="notebook",  font_scale=1.5, rc={'font.family':'AppleGothic'})
sns.palplot(sns.color_palette("muted"))
%matplotlib inline

---
## 1. 데이터 수집(Obtaining the data)

* 데이터 로드

In [2]:
%%writefile ./resource/passenser_raw.data
platform_loc / ride_time / path / info
2-1 / 2017-07-13 07:30 / 동천 -> 강남 / 여3핸정노 남4핸정노 남3잠정이 남3핸세이 여3노세이:판 여5핸평노:판 남3잠정이
2-1 / 2017-07-14 08:25 / 동천 -> 강남 / 남3핸정노 남4핸세이:판 남4핸평노:정 여5잠평노 남3잠평노 여3핸세이 여3핸평노 
2-1 / 2017-07-17 08:17 / 동천 -> 강남 / 여2핸평이:정 여3잠세이:판 남4잠세노 여3핸세노 남3책평이 여4잠세노:판 여3현세이
2-1 / 2017-07-18 08:40 / 동천 -> 강남 / 여2핸평이:정 남3핸세노 남4핸평노:정 남2핸평노 여3잠세노 여2핸평노 여3핸평노:정
2-1 / 2017-07-19 08:20 / 동천 -> 강남 / 여2핸평이:판 여2핸평이 여2잠평노 남4잠정노 여3잠정노 여3핸평이 여4현세이
2-1 / 2017-07-20 08:06 / 동천 -> 강남 / 남5잠세노:정 여3잠평노 남3핸평이:판 여4생세노:정 남3핸세노 여5잠세노 남6생세노
2-1 / 2017-07-21 07:30 / 동천 -> 강남 / 남4핸세노 남4핸평이 여3핸세이 남4정잠노 여4생세노 남3핸평이:정 여3잠세노
2-1 / 2017-07-24 07:35 / 동천 -> 강남 / 여3잠평이 여4핸평노 남4핸정노 여3핸세노 여4핸평노:판 여3핸평이:판 남4핸평노:정 
2-1 / 2017-07-25 07:43 / 동천 -> 강남 / 여4토세노 남5토세노 남4잠세노 남4잠평노:정 남3핸평이 남3잠정이 여4생세노
2-1 / 2017-07-26 08:15 / 동천 -> 강남 / 여3핸평이 남2책평이 여3핸세이 남5핸세노 여5핸세이 남3책세노 여2노평이 
2-1 / 2017-07-27 08:35 / 동천 -> 강남 / 남3생평노:판 여3핸평노 남4잠평노 남4잠정노 여4잠세노:판 남6생세노 남4핸평이:판
2-1 / 2017-07-31 08:25 / 동천 -> 강남 / 남3생평이:판 남4책평노:정 여3핸평이 남4핸세노 여3핸평이 남4핸평이 여2핸평이
2-1 / 2017-08-02 07:12 / 동천 -> 강남 / 여3잠평이 여3핸평이 남4책평노 남4핸평이 남6현세이 남6잠생이 남2핸평이
2-1 / 2017-08-03 08:20 / 동천 -> 강남 / 남3핸평이:판 남3핸평노:정 남4핸세이 남5잠세노 여2핸세이 남3핸평노 여5잠세노
2-1 / 2017-08-08 07:48 / 동천 -> 강남 / 남4핸정이 남4핸평노 여4책세노 남5핸평노 남4핸평이 남6핸세노 여2핸평이
2-1 / 2017-08-09 08:02 / 동천 -> 강남 / 여3잠세노:정 남4잠세노 남4책평이 남4핸정이 남2잠평노 남3핸세노 여3잠세노
2-1 / 2017-08-10 07:35 / 동천 -> 강남 / 남2생세노:정 남2생평노:판 여4잠평노 남4핸평노 남4핸세노 여3핸세노 남3핸세이
2-1 / 2017-08-11 07:12 / 동천 -> 강남 / 남3책평노 남4핸세노 남4핸정노 여3생세노 남3생정노 여3잠세노 여3잠평노:판
2-1 / 2017-08-14 08:40 / 동천 -> 강남 / 여2핸평이 여3잠평노:판 여3핸평이 남4핸세노 남3핸평노 남3잠평노 여3핸세노
2-1 / 2017-08-16 07:35 / 동천 -> 강남 / 여4핸세노 남3핸세노 여5책세노 남3핸평이 남6잠세노 남3핸평이:정 여3잠세노
2-1 / 2017-08-17 08:52 / 동천 -> 강남 / 여3핸평노 남3핸평이:판교 남4핸평이 여5잠세노 남2핸평이:판 여3핸평노 여3핸세노
2-1 / 2017-08-18 08:35 / 동천 -> 강남 / 남4잠평이 여3핸평노 여3잠평노:판 여3토정노 여2토정노 남3토정노 여2핸평노:판
2-1 / 2017-08-22 08:20 / 동천 -> 강남 / 남3잠평노:판 남4핸정노 여2잠평노 여5잠세노 남5잠세노 여2핸세이 여3핸평노
2-1 / 2017-08-23 07:48 / 동천 -> 강남 / 남3핸세노:정 여4핸세노 여3핸세노 여3잠세이 남4핸평노 녀3핸평이 남4잠세이
2-1 / 2017-08-25 07:52 / 동천 -> 강남 / 남4잠평노 남4잠평노:정 여4잠평노 남3핸평노 남6핸세이 남3핸정이 여4핸평이:판
2-1 / 2017-08-28 08:10 / 동천 -> 강남 / 여4핸평노 남3핸세노 여2핸세이 여3책세노 남1핸평이:정 남1생평이:정 여3잠평이
2-1 / 2017-08-29 08:35 / 동천 -> 강남 / 남4잠정이 여4핸세노 남4잠세이 여3잠평노 남4핸평이 여2핸평노 남4현세이
2-1 / 2017-08-30 08:10 / 동천 -> 강남 / 여5책세노 여3핸세이 남5핸평노 여3핸평노 여2핸세이 여3핸평이 여2핸평노
2-1 / 2017-08-31 08:19 / 동천 -> 강남 / 남4핸평이 여3잠평노 여3핸평이 남5핸평이 여4핸세이 남3핸세노 여3핸세노 
2-1 / 2017-09-04 07:52 / 동천 -> 강남 / 남4핸평이:정 남3잠평노 남5잠세이 남4핸평노:판 남4핸정이:정 여3핸평이 여3잠평노 
2-1 / 2017-09-05 08:35 / 동천 -> 강남 / 여2핸평노 여3평핸노:판 여2핸세이 남4책평노 여6책세노 여3핸평이:판 여5잠세노 
2-1 / 2017-09-06 07:40 / 동천 -> 강남 / 남4핸세이 남4핸평이:정 남4잠세노 남4생세이:정 남4핸평노:판교 남4잠정노 여4핸세이
2-1 / 2017-09-07 08:21 / 동천 -> 강남 / 여4잠세노:정 여4핸평노:정 여3잠평이 여3잠평이 여2핸평이 여3핸평노 여4잠평노 
2-1 / 2017-09-08 07:45 / 동천 -> 강남 / 여3잠평노 여3핸평노:정 남3잠평노 남3핸평이:판 여4핸평이 남3잠평이 여3잠세이
2-1 / 2017-09-11 08:30 / 동천 -> 강남 / 남4핸평노 남3핸평이:판 여3핸평이:판 남3잠평노 남1핸평이:정 남1핸평노:정 여3핸평노:판
2-1 / 2017-09-12 08:07 / 동천 -> 강남 / 여3핸평이 남4핸세이:정 여3핸평이 남4핸세이 남4잠평이 여3잠평이 여6토평노 
2-1 / 2017-09-13 07:40 / 동천 -> 강남 / 여3핸평이:판 여4잠평노 여3핸평이 여3잠평이 남3잠정노 여3잠평이 여3핸평이
2-1 / 2017-09-14 07:24 / 동천 -> 강남 / 남3잠평이 남3핸평이 여4핸평노 여2핸평이 여4핸평노 여6생평노 남5생세노:정
2-1 / 2017-09-15 08:20 / 동천 -> 강남 / 여2잠평이:정 여3잠세노 여3핸세노 여4잠세노 남3핸평노 여3잠세노 여3핸평이:판
2-1 / 2017-09-18 07:07 / 동천 -> 강남 / 남5책평노:판 남5핸세노 남3핸평이 남4잠세노 남5책세노 남2핸평노 여3잠평이
2-1 / 2017-09-19 08:28 / 동천 -> 강남 / 남4핸평이 남4핸평이 여3책평이 남4생평이 여3핸평이 여4잠평노 여3핸평노:판
2-1 / 2017-09-20 07:44 / 동천 -> 강남 / 남2핸평이 여3핸평이 여2잠세노 남2잠평이 여4핸세노 남3생세노:정 여3핸평이
2-1 / 2017-09-22 07:18 / 동천 -> 강남 / 여4핸평노:판 남4핸평이 남4잠평노 여3핸평이 여2생평이 남5핸세이 남5핸정노
2-1 / 2017-09-27 07:24 / 동천 -> 강남 / 여3잠평노 여4잠평노:정 남5잠정노 남3핸평노:판 남3잠평노 남3핸평노 여2핸세이
2-1 / 2017-09-28 07:13 / 동천 -> 강남 / 남5책평노:판 남4잠세노 여3핸평노 남5생세이 남4핸세노 남4잠세노 여3핸평노
2-1 / 2017-09-29 08:11 / 동천 -> 강남 / 여3핸세이:정 여3핸평이 남2잠정노 남4핸정이 남4핸평노 남5잠세이 남3핸평노:정

Overwriting ./resource/passenser_raw.data

In [44]:
passenger_ds = pd.read_csv('./resource/passenser_raw.data',sep=" / ", index_col=None, engine='python')
passenger_ds['day'] = passenger_ds.ride_time.apply(lambda x:x[:10])
passenger_ds['hour'] = passenger_ds.ride_time.apply(lambda x:x[-5:])

---
## 2. Scrubbing the data

In [45]:
passenger_ds.head(2)

,platform_loc,ride_time,path,info,day,hour
0,2-1,2017-07-13 07:30,동천 -> 강남,여3핸정노 남4핸정노 남3잠정이 남3핸세이 여3노세이:판 여5핸평노:판 남3잠정이,2017-07-13,07:30
1,2-1,2017-07-14 08:25,동천 -> 강남,남3핸정노 남4핸세이:판 남4핸평노:정 여5잠평노 남3잠평노 여3핸세이 여3핸평노,2017-07-14,08:25

In [46]:
from sklearn.utils import shuffle
passenger_ds = shuffle(passenger_ds, random_state=10)
passenger_ds.head()

,platform_loc,ride_time,path,info,day,hour
30,2-1,2017-09-05 08:35,동천 -> 강남,여2핸평노 여3평핸노:판 여2핸세이 남4책평노 여6책세노 여3핸평이:판 여5잠세노,2017-09-05,08:35
10,2-1,2017-07-27 08:35,동천 -> 강남,남3생평노:판 여3핸평노 남4잠평노 남4잠정노 여4잠세노:판 남6생세노 남4핸평이:판,2017-07-27,08:35
21,2-1,2017-08-18 08:35,동천 -> 강남,남4잠평이 여3핸평노 여3잠평노:판 여3토정노 여2토정노 남3토정노 여2핸평노:판,2017-08-18,08:35
34,2-1,2017-09-11 08:30,동천 -> 강남,남4핸평노 남3핸평이:판 여3핸평이:판 남3잠평노 남1핸평이:정 남1핸평노:정 여3...,2017-09-11,08:30
35,2-1,2017-09-12 08:07,동천 -> 강남,여3핸평이 남4핸세이:정 여3핸평이 남4핸세이 남4잠평이 여3잠평이 여6토평노,2017-09-12,08:07

In [47]:
## convert abbrivation to whole word 
gender_dict = {"남":"남자", "여":"여자"}
to_age = lambda x: int(x) * 10
action_dict = {"핸":"핸드폰보기", "생":"생각중", "토":"토크", "책": "책읽기", "노": "노트북", "잠":"잠자는중"}
dress_code_dict = {"정":"정장", "세":"세미정장", "평":"평상복"}
earphone_dict = {"이":"이어폰:O", "노":"이어폰:X"}
station_dict = {"정":"정자역", "판":"판교역"}

def parsePassengerInfo(info):
    """
    parsing passenger information as a labels 
    
    """
    gender = gender_dict.get(info[0], "남자")
    age = to_age(info[1])
    action = action_dict.get(info[2], "생각중")
    dress = dress_code_dict.get(info[3], "평상복")
    is_earphone = earphone_dict.get(info[4], "이어폰사용안함")

    splited_info = info.split(":")
    exit_station = station_dict.get(splited_info[1], "강남역") if len(splited_info)==2 else "강남역"
    
    return [gender, age, action, dress, is_earphone, exit_station]

In [48]:
parsePassengerInfo("여2핸평이")

['여자', 20, '핸드폰보기', '평상복', '이어폰:O', '강남역']

In [49]:
passenger_info_list = []
for day, hour, info_list in passenger_ds[['day','hour','info']].values:
    passenger_info_list.extend([[day, hour, seat_loc] + parsePassengerInfo(info) \
                                for seat_loc, info in enumerate(info_list.split())] )

In [50]:
passenger_info_list[:2]

[['2017-09-05', '08:35', 0, '여자', 20, '핸드폰보기', '평상복', '이어폰:X', '강남역'],
 ['2017-09-05', '08:35', 1, '여자', 30, '생각중', '평상복', '이어폰:X', '판교역']]

In [51]:
passenger_ds = pd.DataFrame(passenger_info_list
                , columns=['day', 'hour', 'seat_loc', '성별', '나이', '행동', '복장', '이어폰여부', '내리는역'])

In [52]:
print("측정 일수   \t: %4d 일" % len(passenger_ds.day.unique()))
print("측정 승객수  \t: %4d 명" % passenger_ds.shape[0])
print("측정(출근) 시간\t: %s ~ %s" % (passenger_ds.hour.min(),passenger_ds.hour.max()) )

측정 일수   	:   46 일
측정 승객수  	:  322 명
측정(출근) 시간	: 07:07 ~ 08:52

* value grouping

In [53]:
## seat location 
seat_to_group = {
    0:"좌측:사이드",
    1:"좌측:사이드",
    2:"중앙", 
    3:"중앙", 
    4:"중앙",
    5:"우측:사이드", 
    6:"우측:사이드"
}
passenger_ds['좌석위치'] = passenger_ds['seat_loc'].apply(seat_to_group.get)

## station 
passenger_ds['내리는역'] = passenger_ds['내리는역'].apply( lambda x: "강남역" if x == "강남역" else "판교/정자역")

## age 
age_to_group = {
    10:"청년",
    20:"청년",
    30:"중년",
    40:"중년",
    50:"장년",
    60:"장년"
}
passenger_ds['연령대'] = passenger_ds['나이'].apply(age_to_group.get)
passenger_ds['count'] = 1

In [54]:
passenger_ds.to_csv("./resource/passenser.csv", index=None)

In [55]:
pd.read_csv('./resource/passenser.csv').head(10)

,day,hour,seat_loc,성별,나이,행동,복장,이어폰여부,내리는역,좌석위치,연령대,count
0,2017-09-05,08:35,0,여자,20,핸드폰보기,평상복,이어폰:X,강남역,좌측:사이드,청년,1
1,2017-09-05,08:35,1,여자,30,생각중,평상복,이어폰:X,판교/정자역,좌측:사이드,중년,1
2,2017-09-05,08:35,2,여자,20,핸드폰보기,세미정장,이어폰:O,강남역,중앙,청년,1
3,2017-09-05,08:35,3,남자,40,책읽기,평상복,이어폰:X,강남역,중앙,중년,1
4,2017-09-05,08:35,4,여자,60,책읽기,세미정장,이어폰:X,강남역,중앙,장년,1
5,2017-09-05,08:35,5,여자,30,핸드폰보기,평상복,이어폰:O,판교/정자역,우측:사이드,중년,1
6,2017-09-05,08:35,6,여자,50,잠자는중,세미정장,이어폰:X,강남역,우측:사이드,장년,1
7,2017-07-27,08:35,0,남자,30,생각중,평상복,이어폰:X,판교/정자역,좌측:사이드,중년,1
8,2017-07-27,08:35,1,여자,30,핸드폰보기,평상복,이어폰:X,강남역,좌측:사이드,중년,1
9,2017-07-27,08:35,2,남자,40,잠자는중,평상복,이어폰:X,강남역,중앙,중년,1

In [56]:
passenger_ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 322 entries, 0 to 321
Data columns (total 12 columns):
day         322 non-null object
hour        322 non-null object
seat_loc    322 non-null int64
성별          322 non-null object
나이          322 non-null int64
행동          322 non-null object
복장          322 non-null object
이어폰여부       322 non-null object
내리는역        322 non-null object
좌석위치        322 non-null object
연령대         322 non-null object
count       322 non-null int64
dtypes: int64(3), object(9)
memory usage: 30.3+ KB